src/accounts/urls.py
from django.urls import path
from accounts.views import (login_view, logout_view, registration_view, update_view, delete_view, contact_view)

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('registration/', registration_view, name='registration'),
    path('update/', update_view, name='update'),
    path('delete/', delete_view, name='delete'),
    path('contact/', contact_view, name='contact'),
]

src/scraping/urls.py
from django.urls import path
from scraping.views import form_view, list_view, experiments

app_name = 'scraping'

urlpatterns = [
    path('', form_view, name='home'),
    path('list/', list_view, name='vacancy_list'),
    path('experiment/', experiments),

]

src/templates/_inc/caution.html
<h1>Popup/Modal Windows without JavaScript</h1>
<div class="box">
    <a class="button" href="#popup1">Let me Pop up</a>
</div>

<div id="popup1" class="overlay">
    <div class="popup">
        <h2>Here i am</h2>
        <a class="close" href="#">&times;</a>
        <div class="content">
            Thank to pop me out of that button, but now i'm done so you can close this window.
        </div>
    </div>
</div>

src/templates/_inc/else_navbar.html
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #114;">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'scraping:home' %}" id="brand">Job-Search
                /</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
<!--            <div class="collapse navbar-collapse" id="navbarsExampleDefault">-->
                      <ul class="navbar-nav justify-content-end">
                        <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="#">Home</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#">Features</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#">Pricing</a>
                        </li>
                      </ul>

<!--            </div>-->
        </div>
    </nav>
</div>

src/templates/_inc/form.html
<div class="row">
    <div class="col-md-6 mx-auto">
        <form action="{% url 'scraping:vacancy_list' %}" method="GET">
            <div class="form-group">
                {{form.as_p}}
                <div class="d-grid gap-2 col-4 mx-auto">
                    <input class="button-5" type="submit" value="search" id="search">
                </div>
            </div>
        </form>
    </div>
</div>

src/templates/_inc/messages.html
<div class="container">
    <div class="row">
        <div class="col-4 mx-auto my-3">

            {% if messages %}
            {% for message in messages %}

            <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>


            {% endfor %}
            {% endif %}

        </div>
    </div>
</div>

src/templates/_inc/navbar.html
{% url 'accounts:contact' as contact_url %}
{% url 'accounts:update' as update_url %}
{% url 'accounts:login' as login_url %}
{% url 'accounts:registration' as registration_url %}
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #114; border-radius: 15px;">
        <!--bg-light    style="background-color: #a46fa8;"  114  214-->
        <div class="container-fluid">

            <a class="navbar-brand mb-0 h1" href="{% url 'scraping:home' %}" id="brand">Job-Search
                </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="%navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

                <ul class="navbar-nav justify-content-end">

                    {% if user.is_authenticated %}

                    <li class="nav-item">
                        <a class="nav-link {% if request.path == contact_url %} active {% endif %} " href="{% url 'accounts:contact' %}">
                            &nbsp;<i class="fa fa-envelope-o" aria-hidden="true"></i>&nbsp;Обратная связь</a>
                    </li>



                    <li class="nav-item">
                        <a class="nav-link {% if request.path == update_url %} active {% endif %} " href="{% url 'accounts:update' %}">
                            &nbsp;<i class="fa fa-cogs" aria-hidden="true"></i>&nbsp;Настройки</a>
                    </li>




                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">
                            &nbsp;<i class="fa fa-sign-out" aria-hidden="true"></i>&nbsp;Выйти</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == registration_url %} active {% endif %} " href="{% url 'accounts:registration' %}">
                        <i class="fa fa-user-plus" aria-hidden="true"></i>&nbsp;

                            Зарегистрироваться
                        </a>
                    </li>


                    <li class="nav-item">
                        <a class="nav-link {% if request.path == login_url %} active {% endif %} " href="{% url 'accounts:login' %}">
                            <i class="fa fa-sign-in" aria-hidden="true"></i>&nbsp;Войти
                        </a>
                    </li>
                    {% endif %}


                </ul>






                <!--                <form class="d-flex" action="https://www.google.com/search" method="GET">-->
                <!--                    <input class="form-control me-2" type="search" placeholder="google" aria-label="google" name="q">-->
                <!--                    <button class="btn btn-outline-success" type="submit">Search</button>-->
                <!--                </form>-->

        </div>
    </nav>
</div>

src/templates/_inc/pagination.html
{% if page_obj.has_other_pages %}
<br>

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">

        {% if page_obj.number > 3 %}
        <li class="page-item">
            <a class="page-link" href="?city={{city}}&language={{language}}&page=1">
                В начало</a>
        </li>
        &nbsp; &nbsp; &nbsp;
        {% endif %}

        {% if page_obj.has_previous %}

        <li class="page-item">
            <a class="page-link" href="?city={{city}}&language={{language}}&page={{page_obj.previous_page_number}}"
               aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only"></span>
            </a>
        </li>
        {% endif %}

        {% for page in page_obj.paginator.page_range %}

        {% if page_obj.number == page %}
        <li class="page-item active"><a class="page-link" href="#">{{page}}</a></li>

        {% elif page > page_obj.number|add:-3 and page < page_obj.number|add:3 %}
        <li class="page-item"><a class="page-link"
                                 href="?city={{city}}&language={{language}}&page={{page}}">{{page}}</a></li>


        {% endif %}


        {% endfor %}

        {% if page_obj.number|add:2 < page_obj.paginator.num_pages %}
        &nbsp ... &nbsp
        <li class="page-item">
            <a class="page-link" href="?city={{city}}&language={{language}}&page={{page_obj.paginator.num_pages}}">
                {{page_obj.paginator.num_pages}}</a>
        </li>
        {% endif %}


        {% if page_obj.has_next %}


        <li class="page-item">
            <a class="page-link" href="?city={{city}}&language={{language}}&page={{page_obj.next_page_number}}"
               aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only"></span>
            </a>
        </li>

        {% endif %}

    </ul>
</nav>

{% endif %}

src/templates/_inc/reserve_navbar.html
<div class="container">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'scraping:home' %}">JobSearch
            <i class="fa fa-code" aria-hidden="true"></i></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}


                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:update' %}">
                        <i class="fa fa-cogs" aria-hidden="true"></i>&nbsp;Настройки</a>
                </li>


                <li class="nav-item">
                    <a class="nav-link" href="#">
                        |
                    </a>
                </li>


                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">
                        <i class="fa fa-sign-out" aria-hidden="true"></i>&nbsp;Выйти</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:registration' %}">
                        Зарегистрироваться
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        |
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">
                        <i class="fa fa-sign-in" aria-hidden="true"></i>&nbsp;Войти
                    </a>
                </li>
                {% endif %}
            </ul>
<!--            <form class="d-flex" action="https://www.google.com/search" method="GET">-->
<!--                <input class="form-control me-2" type="search" placeholder="google" aria-label="google" name="q">-->
<!--                <button class="btn btn-outline-success" type="submit">Search</button>-->
<!--            </form>-->
        </div>
    </div>
</nav>
</div>

src/templates/_inc/test_pagination.html
<!-- blacksquare blackcurve -->
{% if page_obj.has_other_pages %}
<br>

<div class="paginationn">
    <ul>

        {% if page_obj.number > 3 %}
        <li>
            <a class="blacksquare" href="?city={{city}}&language={{language}}&page=1">
                START</a>
        </li>
        &nbsp; &nbsp; &nbsp;
        {% endif %}

        {% if page_obj.has_previous %}

        <li>
            <a class="blacksquare" href="?city={{city}}&language={{language}}&page={{page_obj.previous_page_number}}">
                <i class="fa fa-caret-left fa-lg" aria-hidden="true"></i>

            </a>
        </li>
        {% endif %}

        {% for page in page_obj.paginator.page_range %}

        {% if page_obj.number == page %}
        <li><a class="blacksquareactive" href="#">{{page}}</a></li>

        {% elif page > page_obj.number|add:-3 and page < page_obj.number|add:3 %}
        <li><a class="blacksquare"
               href="?city={{city}}&language={{language}}&page={{page}}">{{page}}</a></li>


        {% endif %}


        {% endfor %}

        {% if page_obj.number|add:2 < page_obj.paginator.num_pages %}


<i class="fa fa-ellipsis-h fa-lg" aria-hidden="true"></i>

        <li>
            <a class="blacksquare" href="?city={{city}}&language={{language}}&page={{page_obj.paginator.num_pages}}">
                {{page_obj.paginator.num_pages}}</a>
        </li>
        {% endif %}


        {% if page_obj.has_next %}


        <li>
            <a class="blacksquare" href="?city={{city}}&language={{language}}&page={{page_obj.next_page_number}}">
                <i class="fa fa-caret-right fa-lg" aria-hidden="true"></i>
            </a>
        </li>

        {% endif %}

    </ul>
</div>
<br>
{% endif %}